package com.ws101.EcommerceApi.model;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Entity class representing an e-commerce product with validation constraints.
 * 
 * @author Anquilo
 */
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
public class Product {
    
    /**
     * Unique identifier for the product.
     * Auto-generated by the service layer.
     */
    private Long id;
    
    /**
     * Name of the product.
     * Required, must not be blank.
     */
    @NotBlank(message = "Product name is required")
    private String name;
    
    /**
     * Description of the product.
     * Optional field providing additional product details.
     */
    private String description;
    
    /**
     * Price of the product.
     * Required, must be a positive number greater than 0.
     */
    @NotNull(message = "Price is required")
    @Positive(message = "Price must be a positive number")
    private Double price;
    
    /**
     * Category the product belongs to.
     * Required, must not be blank.
     */
    @NotBlank(message = "Category is required")
    private String category;
    
    /**
     * Available stock quantity.
     * Required, must be non-negative (0 or greater).
     */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity must be non-negative")
    private Integer stockQuantity;
    
    /**
     * URL to product image.
     * Optional field for product image reference.
     */
    private String imageUrl;
}